### ISSUE TITLE
Design UX/UI for resource managment in Altinn Studio

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-resource-registry#100]
### Description

We need to define the UI/UX for resource registry management.

Users belonging to a Service Owner organization can create and update resources. 
The resource itself has many [properties](https://docs.altinn.studio/technology/solutions/altinn-platform/authorization/resourceregistry/#resource-attributes). 

The UI needs to include the possibility of setting most of this.

When a Resource is fully defined, it can be published to test or production environments. 

### Additional Information

This is a new concept. The closes scenario now is lenketjenester in TUL.

### Tasks
- [ ] Create design for resource registry management. 

### Acceptance Criterias
- [ ] Possible to create new resources or modify existing
- [ ] All relevant attributes can be set for existing and new resources created
- [ ] Possible to publish resources to a environment (AT,TT02, PROD)
- [ ] Possible to navigate to policy admin from UI
- [ ] Only members of publishing teams can publish
- [ ] ID is validated against ID rules

**Comment by TheTechArch** [comment]
@MetteGrytten driver å rydder i backlog. Dette er vel den orignale issuen.  Det er kanskje naturlig du eier den. Men den er kanskje ferdig
