### ISSUE TITLE
Define structure for Resource Registry Management code on Altinn Studio

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-resource-registry#101]
### Description

Together with team Altinn Studio we need to land the structure of the frontend and backend code for resource registry management

### Additional Information

The current Altinn Studio Designer frontend is split into several applications. 

### Tasks
- [x] Agree on structure for Resource Registry GUI
- [x] Agree on structure for Policy Admin GUI (same app)
- [x] Agree on structure on dashboard changes to navigate to Resource Admin
