### ISSUE TITLE
Build Frontend Application for Resource Managment in Altinn Studio

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-resource-registry#102]
### Description

This task can possibly be split up into several other tasks if it makes sense after #100  is done. 

### Additional Information

Make sure that the structure matches what is expected by the team studio. #101 

### Tasks

- [x] Analyse current structure for existing apps in Altinn Studio 
- [x] Setup main structure of files
- [x] Integrate with other applications in frontend.
- [x] Integrate with API for Listing Resources for ResourceController  https://github.com/Altinn/altinn-studio/issues/9976
The data would be a list of Resources like this https://github.com/Altinn/altinn-resource-registry/blob/main/test/ResourceRegistryTest/Data/Resources/nav_tiltakAvtaleOmArbeidstrening.json

- [x] Integrated with API for open a specific resource. The response will follow resource format https://github.com/Altinn/altinn-resource-registry/blob/main/test/ResourceRegistryTest/Data/Resources/nav_tiltakAvtaleOmArbeidstrening.json
- [x] Integrated with API to save a updated resource. Still with resource format
- [x] Setup a simplified UI to edit main properties like resourceID, name and description while waiting on UX

### Acceptance Criteria
- [x] Possible to navigate from dashboard
