### ISSUE TITLE
GUI og API for å registrere ressurser og tilhørende policyer

### ISSUE THREAD

**Issue by sivaglen** [Altinn/altinn-resource-registry#105]
### Overordnet beskrivelse av behov

Tjenesteeiere skal kunne registrere og forvalte ressurser og deres tilhørende policyer via GUI i Altinn Studio

 
### Overordnet beskrivelse av løsning

- Hver tjenesteeier får et eget repository i Altinn Studio for å håndtere ressurser
- Hver ressurs blir opprettet som en egen folder med et sett filer
- Altinn Studio utvides med nødvendige API for å håndtere 
- Det bygges GUI for å definere og sette egenskaper på ressurs i Altinn Studio
- Det bygges GUI for å definere Policy
- Det bygges integrasjon med ressursregsiteret for å publisere ressurser
- Ressursene eksponeres også via API for å kunne konsumeres av f.eks [Felles Data Katalog](https://fellesdatakatalog.digdir.no/public-services-and-events)

### User Stories

- A user should be able to create a new resource
- A user should be able to define the policy
- A user should be able to validate resource and policy
- A user should be able to publish resources to a selected environment
- Only a user with access to org can modify resources for an org
- Files for a resource should be grouped in folders in the resource repository
- 

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/78
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/100
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/102
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/164
- [ ] https://github.com/Altinn/altinn-studio/issues/5016
- [ ] https://github.com/Altinn/altinn-studio/issues/26
- [x] Build integration with Resource Registry
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/101
- [ ] https://github.com/Altinn/altinn-studio/issues/10188
- [ ] https://github.com/Altinn/altinn-studio/issues/9893
- [ ] https://github.com/Altinn/altinn-studio/issues/10194
- [ ] https://github.com/Altinn/altinn-studio/issues/10203
- [ ] https://github.com/Altinn/altinn-studio/issues/10304
- [ ] https://github.com/Altinn/altinn-studio/issues/10337
- [ ] https://github.com/Altinn/altinn-studio/issues/10389
- [ ] https://github.com/Altinn/altinn-studio/issues/10393
- [ ] https://github.com/Altinn/altinn-studio/issues/10443
- [ ] https://github.com/Altinn/altinn-studio/issues/10451
- [ ] https://github.com/Altinn/altinn-studio/issues/10453
- [ ] https://github.com/Altinn/altinn-studio/issues/10463
- [ ] https://github.com/Altinn/altinn-studio/issues/10482
- [ ] https://github.com/Altinn/altinn-studio/issues/10487
- [ ] https://github.com/Altinn/altinn-studio/issues/10494
- [ ] https://github.com/Altinn/altinn-studio/issues/10498
- [ ] https://github.com/Altinn/altinn-studio/issues/10531
- [ ] https://github.com/Altinn/altinn-studio/issues/10564
- [ ] https://github.com/Altinn/altinn-studio/issues/10569
- [ ] https://github.com/Altinn/altinn-studio/issues/11108
```

**Comment by ekorra** [comment]
### Overordnet beskrivelse av behov
Tjenesteeiere skal kunne registrere og forvalte ressurser og deres tilhørende policyer via GUI.
 
 
### Overordnet beskrivelse av løsning
 
 
### Spørsmål
Gjelder denne både apps, lenktetjenester og eventer?
