### ISSUE TITLE
ResourceRegistry: Sync appsettings and configuration with values.yaml

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-resource-registry#117]
### Description

There are missing and/or differently named appsettings/config values currently in comparison with the environment deploy values (see separate PR for updating values.yaml)

### Tasks

- [x] Cleanup: Remove unused config values from appsettings.json and values.yaml
- [x] Fix and sync naming of Api endpoints with values.yaml and use cluster.local adressing in values.yaml

### Acceptance Criterias

- [x] Resource migration and integration with AccessManagement works

**Comment by jonkjetiloye** [comment]
Tested working in AT21-24, having created a new system resource for MaskinportenSchema delegation. 
Also tested config for authentication with environment-specific Altinn-token and ver2 maskinporten-token working as intended.
