### ISSUE TITLE
Tilby brukerflate for Ressursregister i Altinn Studio

### ISSUE THREAD

**Issue by ekorra** [Altinn/altinn-resource-registry#130]
# Overordnet beskrivelse
Ressursregister er et register, med tilhørende API og brukergrensesnitt i Altinn studio, hvor tjenesteeiere kan registrere sine ressurser (tjenester), tilhørende metadata til ressursen og definere tilgangsstyringsregler (policyer) for ressursen.
Alle tjenester som Altinn Autorisasjon styrer tilgang til i Altinn II vil bli gjort om til ressurser av ulike typer når de flyttes fra Altinn II til Altinn 3.

Ressursregisteret er definert her https://github.com/Altinn/altinn-resource-registry/issues/341

## Behov for brukerflate i Studio
Som tjenesteeier-/tilbyder ønsker jeg administrere ressurser med tilhørende rettigheter fra Altinn studio. Jeg må kunne legge inn beskrivende metadata om ressursen som beskriver dens egenskaper. Ressursene mine skal listes ut slik at de i ettertid enkelt skal kunne mediteres. For hver ressurs må jeg kunne legge inn metadata og tilhørende tilgangsregler. Etter ressursen med tilgangsregler er opprettet ønsker jeg å kunne publisere disse slik at ressursen kan taes i bruk. 
Ressursene med metadata skal tilgjengeliggjøres via API slik at de enkelt kan leses av eksterne feks Felles datakatalog

Tjenesteier trenger sted der det kan registreres ressurser med tilhørende metadata og tilhørende policy
 
# Overordnet beskrivelse av løsning
- En ressurs kan være Altinn 3 app, Altinn Event eller ekstern ressurs/tjeneste
- Hver tjenesteeier får et eget repository i Altinn Studio for å håndtere ressurser
- Hver ressurs blir opprettet som en egen folder med et sett filer
- Altinn Studio utvides med nødvendige API for å håndtere disse filene
- Det bygges GUI for å definere og sette egenskaper på ressurs i Altinn Studio
- Det bygges GUI for å definere Policy
- Det bygges integrasjon med ressursregsiteret for å publisere ressurser
- Ressursene eksponeres også via API for å kunne konsumeres av f.eks [Felles Data Katalog](https://fellesdatakatalog.digdir.no/public-services-and-events) 
- Gamle ressurser må kunne konverteres med delegeringsinfo slik at brukere får tilgang til ressurs

## Krav
- [x] Brukere i Altinn Studio skal få oversikt over ressurser som er definert i Altinn Studio
- [x] Det skal være mulig å opprette nye ressurser fra Altinn Studio Dashboard
- [x] Man skal kunne editere ressurser
- [x] Altinn Studio skal validere innholdet i ressursene slik at de tilfredstiller kravene som ressursregisteret har til en ressurs
- [x] Det skal være mulig å definere policies ved hjelp av GUI
- [x] GUI for policy må validere at policy inneholder nødvendige innhold for å kunne fungere
- [x] Format på ressursid må være i henhold til standard (a-Z0-9 _ -)
- [x] Det må kreves innhold for tittel, description og rights description for bokmål, nynorsk og engelsk
- [x] Kun owners for org i Gitea eller medlemmer av teamet Resources har rettighet til å endre på ressurser
- [x] Det skal være mulig å publisere til alle miljø org har tilgang til.  (TT02, PROD, AT for TTD) 
- [x] Man må være medlem av Resources-Publish-TT02 osv for å kunne publisere til miljø
- [x] Kun ressurser som er sjekket inn og commited til GITEA kan publiseres
- [x] I Altinn studio skal man kreve et versjonsnr før publisering

# Tilknyttede oppgaver

```[tasklist]
### Analyse
- [ ] #143
- [ ] #139
- [ ] #140
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/199
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/200
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/100
- [ ] https://github.com/Altinn/altinn-studio/issues/9498
```

```[tasklist]
### Features
- [ ] Tilgjengeliggjøre metadata for Felles datakatalog
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/105
```
