### ISSUE TITLE
Resource Rights Registry - Flytte funksjonalitet for tjenesteeeierstyrt rettighetsregister fra Altinn 2 til Altinn 3

### ISSUE THREAD

**Issue by ekorra** [Altinn/altinn-resource-registry#131]
# Overordnet beskrivelse av behov
Ressurseier skal kunne velge/styre hvilke organisasjon eller person som kan få tilgang til en ressurs
 
 
# Overordnet beskrivelse av løsning
Generelt er alle ressurser i Ressursregisteret tilgjengelig for alle personer og organisasjoner av en gitt type.
Resource Rights Registry gjør det mulig for en eier av en ressurs i Ressursregstert til å velge hvilke organisasjon eller person en tjeneste skal være tilgjengelig for. 

# Estimat/Omfang
Denne oppgaven bør designmessig løses i forbindelse med #130 noe som vil gi mindre designarbeid

### Spørsmål
Egen komponent eller del av Ressursregister

This covers both the creation of a resource rights registry and integrating it from PDP and Rights API.

### Analysis & Refinement

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/317
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/211
```

### Features

```[tasklist]
### Features
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/338
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/339
- [ ] https://github.com/Altinn/altinn-authorization/issues/543
```
