### ISSUE TITLE
Explore stakeholder needs for internal product alignment

### ISSUE THREAD

**Issue by sorensensig** [Altinn/altinn-resource-registry#141]
### Description

Run a co-design workshop with Felles Datakatalog (FDK) to understand their needs as a stakeholder of the Resource Registry.

[workshop figma board](https://www.figma.com/file/HtE9jPofejEe85z2Ak5MiB/Workshop.-FDK%3A-Resource-Registry?node-id=1%3A4766&t=pEWmRjuG4GfmL0K6-1) 🔐 (only accessible to Digdir users)

### In scope

- Understanding stakeholder needs, potential use of, ideas and concerns about the concept
- Co-design figma sketches that shows what it might look like and how it might work
- Gather feedback for the product team

### Additional Information

```[tasklist]
### Tasks
- [x] Create the workshop in figma
- [x] Invite participants
- [x] Run the workshop
- [x] Analyse insights
- [x] Present findings back to the team
```

#### Findings:

- Several standards they have to align with (EUROVOC, LOS, EU themes)
- Importance of events and journeys for cross-government experience
- The continued importance of common terminology to reduce legal ambiguity/make it easier to comply with legislation and detect when, for example, a service is not in accordance with legislation
- Metadata quality strategies with users
- Advice around certain fields (i.e. contact information and workplace)
- Potential need to add support for multi lingual descriptions

### Conclusion

FDK expressed a desire to work closely with us in the future and be part of the solution
 
Next steps flagged as:
- Talking with Jørgen about use of resources in our portals
- Focus on the users of this system
