### ISSUE TITLE
Hold co-design workshop with service owner to understand user needs

### ISSUE THREAD

**Issue by sorensensig** [Altinn/altinn-resource-registry#142]
### Description

Run a co-design workshop with Brønnøysundsregistrene (BR) to understand their needs as a future user of the Resource Registry.

[workshop figma board](https://www.figma.com/file/01unZBzPH658MkuT0mhUpK/Workshop-med-BR---Ressurs-Registeret?node-id=0%3A1&t=tAcqtQNYZgyeIMRL-1) 🔐 (only accessible to Digdir users)

### In scope

- Understanding user needs, potential use of, ideas and concerns about the concept
- Co-design figma sketches that shows what it might look like and how it might work
- Gather feedback for the product team

### Additional Information

```[tasklist]
### Tasks
- [x] Create the workshop in figma
- [x] Invite participants
- [x] Run the workshop
- [x] Analyse insights
- [x] Present findings back to the team
```

#### Findings

- From their perspective, developers are not the ones to set up or create policies - this is more likely to be the legal stakeholders
- Having a separate tab in studio as a resource tab was flagged as useful
- Question: Who should be able to see or use resources, internally and/or externally?
- The solution must be accessible to non-technical users (for example, legal stakeholders)
- Multi-select across rule settings is desirable: "I don't want to add a new rule for every role. It would be nice to in the same step, select 15 roles with 3 separate actions for 1 resource"
- Previewing what your input will look like based on where it is used (Portal, Altinn etc) during rule creation is very useful to developers 

### Conclusion

Next steps:
- Finalise the personas and Jobs to be Done started in the workshop

**Comment by indiamaydesign** [comment]
@ekorra this is our high level summary of the workshop with developers from a service owner perspective, for us to bring up on Monday with the team

**Comment by indiamaydesign** [comment]
@sorensensig we discussed next steps as talking with service owners that are using linked services (lenketjenester)

- [ ] Source several additional service owners that use _lenketjenester_
- [ ] Hold workshops on concept and UI
- [ ] Report back
