### ISSUE TITLE
Hold Clear Language workshop with product team to align goals and vision

### ISSUE THREAD

**Issue by indiamaydesign** [Altinn/altinn-resource-registry#143]
### Description

Using [Digdir's Klarspråk](https://www.digdir.no/klart-sprak/rettleiar-om-klarsprak-i-utvikling-av-digitale-tenester/3564) workshop and guide for[ the beginning of a project](https://www.digdir.no/klart-sprak/klart-sprak-i-oppstart-av-prosjektet/3557), the product team will define our expectations as a team and for the product.

Our learnings from the process will be given back to the Klarspråk team to help them iterate on the workshops and guide.

### Tasks

```[tasklist]
### Tasks
- [x] Prepare the workshop in Figma
- [x] Hold Part 1: What do we know about the service and what do we know about the project
- [x] Hold Part 2: Common terminology
- [x] Hold Part 3: Summary of service
- [x] Refer back to the workshop terms and decisions throughout the project
```
