### ISSUE TITLE
Create CodeList Api for resource Registry

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-resource-registry#156]
### Description

The resource registry would need to have some codelist available for selecting values for the resource enties

### Additional Information

The CVSP standard gives guidelines of some of this

#### Spatial information
This property represents that area(s) a Public Service is likely to be available only within, typically the area(s) covered by a particular public authority.

Regarding usage of controlled vocabularies, the following requirements apply:

At least one value shall be chosen from the following controlled vocabularies: [Continent](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/continent); [Country](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/country); [Place](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/place); [GeoNames](http://sws.geonames.org/).

To specify spatial coverage in Norway, the Norwegian Mapping Authority’s controlled vocabulary [Administrative units](https://data.geonorge.no/administrativeEnheter/nasjon/doc/173163) should be used.

#### Type

The possible values for this property are described in EU’s controlled vocabulary [Main activity](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/main-activity).

The values is only available in EU languages. We need to add Norwegian. 
The XML can be downloaded in [XML format](https://op.europa.eu/o/opportal-service/euvoc-download-handler?cellarURI=http%3A%2F%2Fpublications.europa.eu%2Fresource%2Fcellar%2Fc37a3d76-3e74-11ed-92ed-01aa75ed71a1.0001.04%2FDOC_1&fileName=main-activity.xml)

#### Status

Norwegian extension: The value shall be chosen from [ADMS Status Vocabulary (linked resource in RDF)](http://purl.org/adms/status/).

The number of values is limited

#### Thematic area
At least one value shall be chosen from EU’s controlled vocabulary [EuroVoc](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://eurovoc.europa.eu/100141). [Los](https://psi.norge.no/los/) may be used in addition.

API informasjonsforvaltning
https://data.norge.no/reference-data/eu/eurovocs
https://data.norge.no/reference-data/los/themes-and-words

#### Sector

This property represents the industry or sector a Public Service relates to, or is intended for. Note that a single Public Service may relate to multiple sectors.

The possible values for this property are described in the controlled vocabulary [Data theme Authority Table](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/data-theme) of the Publications Office.

API informasjonsforvaltning

https://data.norge.no/reference-data/eu/data-themes

#### Resource Registry Type

This is our Altinn version of this. We have not yet defined all possible. 

#### Resource Registry Status

What kind of status do we need? 

#### Available API from informasjonsforvaltning

Informasjonsforvaltning supports an API for 
Thematic Area, Sector and Los and might be used as backend for our API.

Investigate the availability for this

https://github.com/Informasjonsforvaltning/fdk-reference-data/blob/main/src/main/resources/openapi/openapi.yaml

### Tasks

- [ ] Identify what is the needed datasources needed for spatial information
- [ ] Design UX for this area
- [ ] Implement and expose API to UI to select
- [ ] Identify the datasource for type
- [ ] Design UX for type
- [ ] Implement and expose APIO for UI to select from
- [ ] Identify the datasource for CPSV Status 
- [ ] Design UX for this input
- [ ] Implement and expose API for CPSV status values
- [ ] Identify the datasource for thematic area. Do we need to use los in addition to EUROVOC?
- [ ] Design UX for this 
- [ ] Implement API and expose to UX
- [ ] Identify the datasource for sector
- [ ] Design UX for this 
- [ ] Implement API and expose to UX

**Comment by TheTechArch** [comment]
Closes since there is currently no need.
