### ISSUE TITLE
Integrate Resource Registry Admin in to Altinn Studio Designer

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-resource-registry#164]
### Description

We need to integrate UI created in #102  in to designer so we can navigate to an URL in Designer where this new frontend is loaded. 

### Tasks

- [x] Update NGINX to a new path that routes to /resourceadmin/
- [x] Add new resourceadmin controller with view
- [x] Add frontend build to altinn studio designer pipeline that pushes the javascript file to the "correct" location

### Acceptance Criterias

- [x] It is possible to navigate to /resourceadmin/ in Altinn Studio Designer and the new React frontend for Resource Admin is loaded

**Comment by TheTechArch** [comment]
Complete
