### ISSUE TITLE
Display resources in Altinn Studio dashboard

### ISSUE THREAD

**Issue by ekorra** [Altinn/altinn-resource-registry#168]
### Description

As a resource owner I want to be able to handle my resources through Altinn Studio so I have one place where I can get a total overview of them. I should be able to se a list of registered resources and their publication status.
From the view I should be able to add new resources and select existing ones for editing or deleting

### Additional Information

```[tasklist]
### Tasks
- [ ] #102
- [x] Display list of resources
- [x] Show type of resource for each resource (app, event, external)
- [x] Show buttons for editing/open resource in app
- [x] Show button for viewing resource file
- [x] Show button to create new resource
- [ ] K6 test functions
- [ ] Cypress tests of UI
```

```[tasklist]
### Acceptance Criterias
- [ ] Display list of resources
- [ ] Show type of resource for each resource (app, event, external)
- [ ] Show buttons for editing/open resource in app
- [ ] Show button for viewing resource file
- [ ] Show button to create new resource
```
