### ISSUE TITLE
Tilby ressursadministrasjon i Altinn Studio

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-resource-registry#176]
### Beskrivelse

I Altinn Studio skal tjenesteeiere kunne registrere og oppdatere ressurser til ressurs registeret. Selve ressursregisteret er definert her https://github.com/Altinn/altinn-resource-registry/issues/341

Konseptet er at hver tjenesteeier har sitt eget repository hvor de definerer alle frittstående ressurser som skal registreres i ressursregisteret via Altinn Studio. Det er også mulig å registrere ressurser direkte via API.

Det vil være mulig å opprette ressurser basert på lenketjenester i Altinn 2

### Aksptansekrav

- Det skal være mulig å opprette nye ressurser
- Det skal være mulig å sette autorisasjonspolicy for ressurs
- Det skal være mulig å publisere ressurs til aktuelle miljø for gitt tjenesteeier (TT02, Prod, AT)
- Det skal være mulig å endre på ressurser/policy
- Man skal ha validering på ressurs/policy
- Man skal kunne opprette ressurs basert på lenketjenester i Altinn 2
- Det skal være mulig å migrere over rettigheter fra Altinn 2 lenketjenester til Altinn 3 ressurs
- Det skal være mulig å definere ressurser av forskjellige typer (Generic, ApiScheme)

This epic links all analysis & development tasks for #105

### Repo

- [ ] Tool for setup initial repo for all orsgs

```[tasklist]
### Analyse og UX design
- [ ] https://github.com/Altinn/altinn-studio/issues/10880
- [ ] https://github.com/Altinn/altinn-studio/issues/10893
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/78
```

### Features Ressursadmin i Altinn Studio

```[tasklist]
### Features
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/102
- [ ] https://github.com/Altinn/altinn-studio/issues/9835
- [ ] https://github.com/Altinn/altinn-studio/issues/10715
- [ ] https://github.com/Altinn/altinn-studio/issues/10997
- [ ] https://github.com/Altinn/altinn-studio/issues/10497
```

```[tasklist]
### Dokumentasjon
- [ ] Beskriv opprettelse og publisreing av generiske ressurser
- [ ] Beskriv opprettelse og publisering av API Scheme
- [ ] Beskriv opprettelse og publisering av Broker services
- [ ] Beskriv Migreing av lenktjeneste til Altinn 3 inkludert delegering
```

**Comment by Nyeng** [comment]
Dette er tatt i bruk, alt annet er teknisk gjeld / bugs
