### ISSUE TITLE
Add Health check endpoint

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-resource-registry#18]
### Description

We need health check endpoint in the application

### Additional Information

Look at storage
https://github.com/Altinn/altinn-storage/tree/main/src/Storage/Health
https://github.com/Altinn/altinn-storage/blob/main/src/Storage/Program.cs#L181
https://github.com/Altinn/altinn-storage/blob/main/src/Storage/Program.cs#L326

### Tasks

- [ ] Add health check endpoint (look at other components) 

### Acceptance Criteria
- [x] Health check added to application
- [x] Healt check telemetry added
- [x] Health check configuration in Kubernetes
