### ISSUE TITLE
Overview over subject / resources

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-resource-registry#185]
### Description

We need to create a storage with API to store relations between subjects and resources on top level so we can easy get an overview of what a subject has access to.

This should support

- The possibility of presenting a list of resources that a specific subject(accessgroup/role) get access to
- Can identify on top level which resources a user/systemuser/ has access to

####  Data Model

The stored model will be very simple.

{
"Subject": "urn:altinn:rolecode:dagl",
"Resource":"urn:altinn:resource:app_skd_flyttemelding"
"ResourceOwner": "skd"
}

### Update on Policy Update Resource Registry

When a policy is published or updated, the endpoint in the resource registry needs to update the table with the subject /resource relationship.

https://github.com/Altinn/altinn-resource-registry/blob/main/src/Altinn.ResourceRegistry.Core/Services/ResourceRegistryService.cs#L98

### Update App Policy Relationship.

When Altinn Studio publishes 

https://github.com/Altinn/altinn-authorization/blob/main/src/Authorization/Controllers/PolicyController.cs#L52

The data for the given resource needs to be updated. 

- Get current status for resource
- See of there any role changes
- Update (add/delete mismatch)

#### API Design

The response object for API will be list of services resources

List<ServiceResourceBE>   The model is seen [here](https://github.com/Altinn/altinn-resource-registry/blob/main/src/Altinn.ResourceRegistry.Core/Models/ServiceResource.cs) 

Input will be a List<string> where the string value is the subject key

### Additional Information

The resource object should be taken from a cache with long lifetime.

####

### Tasks

- [ ] Build API in Resource Registry to list ResourcesBy subject
- [ ] Update Import Policy for App resources to update the table with info
- [ ] Update Import Policy for Resource registry resource to update table with info
- [ ] Create job that parse through every existing policies to populate based on resource policies and app policies. 

### Acceptance Criteria

- [ ] Can return a list of Resources based on subject
- [ ] The subject needs to be given with full format.  
- [ ] Caching is implemented on several levels. Both for the full resource object and the full resource object list.

**Comment by Nyeng** [comment]
Rullet ut i test og prod, og tatt i bruk av Dialogporten.
