### ISSUE TITLE
Common metadata endpoint for (available) resources/apps/services

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-resource-registry#186]
### Description

We need a common endpoint for resource, app and A2 service metadata, which can be used to build the new single rights delegation feature (and later on in the new delegation request feature).

- Altinn 2 service metadata is already available through SBL bridge (metadata/api/availableServices).
- Resource metadata can be retrieved locally from the resource-registry.
- App metadata (if not also made available locally in the resource-registry) can be retrieved from storage (storage/api/v1/applications/).

The sources of metadata should be mapped to the resource-registry's defined ServiceResource model.

### Tasks

Overall:
- [ ] Caching

Altinn 2 service metadata:
- [ ] SBL client implementation for available services metadata
- [ ] Mapper for AvailableService -> ServiceResource model

Altinn 3 apps metadata:
- [ ] Storage client implementation for applications metadata
- [ ] Mapper for Application -> ServiceResource model

Resource metadata:
- [ ] Using the existing Search operation

**Comment by Nyeng** [comment]
@jonkjetiloye vet du hva status her, eller on den evt kan lukkes?

**Comment by annerisbakk** [comment]
Lukkes etter tilbakemelding fra @TheTechArch
