### ISSUE TITLE
Create components for policy related wireframes

### ISSUE THREAD

**Issue by sorensensig** [Altinn/altinn-resource-registry#196]
### Description

This chore includes components to be designed for the policy page in the resource registry.

### Tasks

- [x] show list of available policy actions and CTA to select actions
- [x] show list of available policy subjects and CTA to select subjects
- [x] show selected resource and CTA to narrow down resource
- [x] textfield to provide reasoning for the ruleset
- [x] CTA to add extra rulesets
- [x] CTA to copy ruleset
- [x] CTA to delete ruleset
- [ ] radio button to select login security level to access the service
