### ISSUE TITLE
Create components for resource related wireframes

### ISSUE THREAD

**Issue by sorensensig** [Altinn/altinn-resource-registry#197]
### Description

This chore includes components to be designed for the resource pages in the resource registry.

Not included:
- policy components
- dashboard components
- migration components

### Tasks

- [x] show list of available resource types and CTA to select resource type
- [x] textfield for filling out resource title
- [x] text to show ID and CTA to edit/overwrite ID
- [x] textfield for filling out resource description
- [x] textfield for filling out keywords
- [x] textfield to fill in delegation text
- [x] options to select available language
- [x] textfield to fill in homepage url
- [x] switch to show in public catalogues
- [x] dropdown for thematic area
- [x] dropdown for sector that the service is related to
- [x] dropdown for organisation type of service
- [x] dropdown for geographic area

**Comment by indiamaydesign** [comment]
Additional work will need to be done on content design and clear/plain language for filling out a resource. This is particularly important for CPSV standards that are drop down, including:

**Thematic area** - skos: concept. From our documentation "This property represents the Thematic Area of a Public Service as described in a controlled vocabulary". 
Notes: This is either [Eurovoc](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://eurovoc.europa.eu/100141) or [Los](https://psi.norge.no/los/) 

**Sector** - skos: concept. From our documentation: "This property represents the industry or sector a Public Service relates to, or is intended for. Note that a single Public Service may relate to multiple sector"
Notes: Whom this service is meant for. In our use case, Næringskoder (NACE) is considered too focused on industry by EU, [data theme](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/data-theme) is less industry focused. The outcome to this will come soon according to the CPSV team

**Organisation type of service** - in our documentation "This property represents the Type of a Public Service as described in a controlled vocabulary".
Other notes: Only for public services - describing the function of services. Potentially similar to[ Functions of Government ](https://semiceu.github.io/CPSV-AP/releases/3.1.0/#Public%20Service)in CPSV. Or [main activity](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/main-activity), but this vocabulary is lacking the ability to describe non-public services


**Geographic area/spatial** - dct:Location - in our documentation "A Public Service is likely to be available only within a given area, typically the area covered by a particular public authority.
dct:Location
The property is used to refer to a geographic area covered by the service.
Example: «Skjenkebevilling (i Brønnøy kommune)» har Brønnøy kommune i Norge som dekningsområde."
Notes: Preference is for ATU (doesn't have Norway, then NUTS (does have Norway) and other options. Listed on [CPSV page](https://semiceu.github.io/CPSV-AP/releases/3.1.0/)


The [CPSV Github ](https://semiceu.github.io/CPSV-AP/releases/3.1.0/)is also an invaluable resource at this time for these categories as is Jim Yang in Digdir who is collaborating on this
