### ISSUE TITLE
Create components for dashboard related wireframes

### ISSUE THREAD

**Issue by sorensensig** [Altinn/altinn-resource-registry#198]
### Description

This chore includes components to be designed for the dashboard page in the resource registry.

### Tasks

- [x] CTA to create a new resource
- [x] CTA to migrate an existing resource
- [x] searchfield to filter through the resource list
- [x] list of existing resources (includes title, created by, last changed, policy status, edit button and alternative options)
- [x] git-bar for gitea related actions, such as fetch and upload changes
