### ISSUE TITLE
Create components for migration related wireframes

### ISSUE THREAD

**Issue by sorensensig** [Altinn/altinn-resource-registry#201]
### Description

This chore includes components to be designed for the migration page(s) in the resource registry.

Not included:

policy components
dashboard components
resource components

### Sketches/flows

**Publish**
1. a Error message on publish page because of unresolved issues in the resource and policy pages
![Image](https://github.com/Altinn/altinn-resource-registry/assets/19344884/65e4383b-efc7-49b4-8b31-ff80d8c0a2b2)

1. b Success message from previous steps (correctly filling out resource and policy pages), putting in version number to migrate
![Image](https://github.com/Altinn/altinn-resource-registry/assets/19344884/13f49cc4-9780-4c51-9836-1f9720a90166)

**Migration**
2. Steps to manually tick to confirm that you have done all of the steps for checking the resource, policy, publishing options and are ready for migration. Additional blue panel for automated process
![Image](https://github.com/Altinn/altinn-resource-registry/assets/19344884/24c5fa3c-064a-4f95-b1f2-8dfd42556e08)

3. After migration has begun, this page shows the status and lets the user download a backup before they can choose to turn off their Altinn II service and delete delegations after x-amount of time
![Image](https://github.com/Altinn/altinn-resource-registry/assets/19344884/f9187d2e-5127-4357-a2db-9fe511b47cde)

**Alternatives**
Additional panel options for migration:
 
![Image](https://github.com/Altinn/altinn-resource-registry/assets/19344884/fecc7e39-432b-4f4f-9769-440f2f061084)

![Image](https://github.com/Altinn/altinn-resource-registry/assets/19344884/aa532bfd-49b1-428c-b23d-63fd3a89c7f2)

### Tasks

- [x] Plan flows with architect and devs
- [x] Create first pass in Figma
- [x] Review with devs
- [ ] Alignment with Studio
- [ ] User testing
- [ ] Refine design
- [ ] UU/Wcag

**Comment by indiamaydesign** [comment]
@ekorra I think this should still be open because William will be finishing up this design and Studio will most likely help with testing it if I understand correctly

**Comment by mgunnerud** [comment]
Closing this one, as migration of delegations has already been done in prod
