### ISSUE TITLE
Add Maskinporten authentication to Resource Admin API

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-resource-registry#21]
### Description

We need to add authentication of exchanged maskinporten tokens

### Additional Information

This is similar to storage component that support maskinporten.

### Tasks
- [ ] Add maskinporten authentication to API for creating and updating resources with policies

### Acceptance Criteria
- [ ] Need to verify scope defined for resource registry to use the API
- [ ] Does not need to be an org. (tjenesteeier)

**Comment by TheTechArch** [comment]
Duplicate
