### ISSUE TITLE
Technical analysis of migration of link services to resource register

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-resource-registry#216]
### Description

This analysis describes what is needed to allow for self-service of migration of link services from Altinn 2

GUI for creating a new resource based on existing service in Altinn 2

![image](https://github.com/Altinn/altinn-resource-registry/assets/13309071/689f42c3-3757-4486-93c9-3272ba1e5858)

Migrate page to see status of resource and trigger migration of delegations

![image](https://github.com/Altinn/altinn-resource-registry/assets/13309071/8b50ca73-71d4-4570-bdcd-f167938c2bf0)

![docs.altinn.studio/authorization/linkservicedependencies.drawio.svg](https://docs.altinn.studio/authorization/linkservicedependencies.drawio.svg)

## Step 1. Creation of Resources in Altinn Studio based on metadata from Altinn 2

By using the AvailableService API, we can get the name and title of the service together with the external service code and edition Code.   

This can be used to create the initial resource information. 

- [ ] API for creating Policy https://github.com/Altinn/altinn-studio/issues/10667
- [ ] API for getting metadata https://github.com/Altinn/altinn-studio/issues/10667

## Step 2.  Deploying Resource to Resource Registry

 The next step is to deploy the APi

- [ ] Functionality to publish in UI https://github.com/Altinn/altinn-studio/issues/10670
- [ ] API in Altinn Studio to publish resources https://github.com/Altinn/altinn-studio/issues/10337
- [x] API in Resource Registry to publish  

## Step 3. Verifying Resources and integration

The service owner must validate integration with the new PDP endpoint in this step.

- [ ] PDP endpoint for external usage https://github.com/Altinn/altinn-authorization/issues/448
- [ ] Optional? Rights API for service owner usage

## Step 5 Disabling service in Altinn 3
 
Before starting the migration of delegations, the service owner should prevent changes in the delegated rights

To do this, the service owner needs to disable the service

- [ ] API to disable delegation of service  https://github.com/Altinn/altinn-resource-registry/issues/215
- [ ] Functionality in Altinn Studio to disable service https://github.com/Altinn/altinn-studio/issues/10670

## Step 6 Migration delegation 

The next step is to migrate the delegations.

The service owner can set a time 

- [ ] Create ExportDelegationBatch https://github.com/Altinn/altinn-access-management/issues/579
- [ ] API to trigger batch job https://github.com/Altinn/altinn-resource-registry/issues/214
- [ ] API to verify status of batch job https://github.com/Altinn/altinn-resource-registry/issues/214

## Step 7 Removing Altinn 3 delegation data

The last step is to remove all delegations from Altinn 2

- [ ] API to disable delegations https://github.com/Altinn/altinn-resource-registry/issues/232
- [ ] API to delete delegations https://github.com/Altinn/altinn-resource-registry/issues/232

## Depending tasks as part of single rights delegation

- Single rights delegation in Altinn 3
- Update rights overview in Altinn 2 to includes single rights from Altinn 3

**Comment by TheTechArch** [comment]
Closes this. Functionality in production
