### ISSUE TITLE
Create job to export data from Altinn 2 and import to Altinn 3

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-resource-registry#22]
### Description

Create job to export data from Altinn 2 and import to Altinn 2

### Tasks

- [x] Define how to extract data from Altinn 2 authorization rules.  
- [x] Create a job that converts rules to XACML 
- [x] Define a batch framework for this kind of job 
- [x] Define how to map actions Altinn 2 > Altinn 3
- [x] Define hot to map scopes to new Altinn 3 policy (delegated)

### Acceptance Criterias

- Resources from Altinn 2 is created in Altinn 3
- XACML Policy is created
- Possible to copy delegations

**Comment by annerisbakk** [comment]
Verifiseres i TT
