### ISSUE TITLE
As a employer I should be able to modify resources from GUI

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-resource-registry#25]
### Description

We should consider providing some gui to allow employers of a resource owner to administrate resources.

### Additional Information

We need to figure out how they log in and how we authorize it. 

Should we have a repository just like an app in Altinn Studio?

And use groups there?

### Tasks

- [ ] Define concept how to administrate resources in GUI
- [ ] Create development tasks

### Acceptance Criterias
- [ ] Plan for adding functionality is in place

**Comment by sivaglen** [comment]
@TheTechArch - er denne issuen fortsatt aktuell eller er den en duplikat av https://github.com/Altinn/altinn-resource-registry/issues/105?

**Comment by TheTechArch** [comment]
Its duplicate
