### ISSUE TITLE
Bruno Tests for Resource Registry (altinn-resource-registry)

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-resource-registry#250]
### Description

Resource registry component does not have Bruno-tests

#### Scenarios that need to be covered

- Open resource
- Update Resource
- List resources
- Create Resources with errors
- Update Policy
- Get Policy
- Update policy with errors (incorrect ressurs id. +++) 
- Try to update resources not allowed to (not admin scope, not correct org) 
- Search API
- Export API. Verify
- Resourceownerlist

### Tasks

- [ ] Implement K6 tests for resourcecontroller
- [ ] Implement K6 test for resourceownercontroller
- [ ] Update/Configure pipeline for K6 tests for resource registry

### Acceptance Criteria

- [ ] Tests cover all the operations in Resource registry
- [ ] Pipeline runs the tests in at environment

**Comment by Nyeng** [comment]
Burde vi hatt noe her @TheTechArch? Koster det mye å sette opp noe enkelt for dette tror du mtp testdata?  (vet ikke om det er enkelt å opprette og publisere ressurser direkte via API etc)

**Comment by annerisbakk** [comment]
Lukkes. Test ivaretas av senere funksjonalitet.
