### ISSUE TITLE
RRR Admin CRUD

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-resource-registry#253]
### Description

We need an API to let resource owners administrate the resource rights registry. 

As a service owner, you can add, remove, or update rights for a given organization/person for a given resource.

This data will be used in PDP to deny/allow access to a resource that has enabled RRR.

It will also disable access to delegating rights relegated to resources.

#### Model

{
"RRRID": "9726e418-911e-4c55-a2e5-186446fa0b7c"
"Resource": "urn:altinn:resource:skd_skattemelding,
"PartyID": 1234325,
"Party": "orgno:923488",
"Action": ["Read","Write"],
"RequiredClaim": "urn:scope:flyttemelding"
}

### Additional Information

When adding rights to a resource, the API needs to verify that.

- Authenticated org has scope for resource registry
- Authenticated org owns the resource in question
- Verify that the resource has enabled RRR
- Find the correct party and add it to row for performance lookup
- When deleting a row, we need to add it do a history tabell

```[tasklist]
### Tasks
- [x] Setup ResourceRegistry Controller
- [x] Setup Resource Registry Database
- [x] Setup Controller authorization
- [x] Create Service layer
- [x] Create and handle optimistic concurrency to the database
- [x] Create a method to create an entry to RRR
- [x] Create a method to delete entries to RRR based on ID
- [x] Add list of resource connections to access list info DTO (nullable)
- [x] Integrate with registry to exchange party-guids for organization numbers
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/418
```

```[tasklist]
### API methods
- [x] GET /resourceregistry/api/v1/access-lists/{owner}
- [x] GET /resourceregistry/api/v1/access-lists/{owner}/{identifier}
- [x] DELETE /resourceregistry/api/v1/access-lists/{owner}/{identifier}
- [x] PUT /resourceregistry/api/v1/access-lists/{owner}/{identifier}
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/417
- [x] GET /resourceregistry/api/v1/access-lists/{owner}/{identifier}/members
- [x] PUT /resourceregistry/api/v1/access-lists/{owner}/{identifier}/members
- [x] POST /resourceregistry/api/v1/access-lists/{owner}/{identifier}/members
- [x] DELETE /resourceregistry/api/v1/access-lists/{owner}/{identifier}/members
- [x] GET /resourceregistry/api/v1/access-lists/{owner}/{identifier}/resource-connections
- [x] PUT /resourceregistry/api/v1/access-lists/{owner}/{identifier}/resource-connections/{resourceIdentifier}
- [x] DELETE /resourceregistry/api/v1/access-lists/{owner}/{identifier}/resource-connections/{resourceIdentifier}
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/416
```

```[tasklist]
### Known bugs
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/421
```

### Acceptance Criteria

- [x] Service Owners can add RRR data only for resources owned by them
- [x] Service owner can modify RRR data only for resources owned by them
- [x] Only orgs with write scope to resource registry is allowed to access RRR api

### Related
- https://github.com/Altinn/altinn-register/issues/170

**Comment by Alxandr** [comment]
Related: https://github.com/Altinn/altinn-register/pull/180
