### ISSUE TITLE
Som tjenesteeier av Delegerbar API ressurs ønsker jeg en måte å kunne registrere/endre ressurs uten å bruke API

### ISSUE THREAD

**Issue by sivaglen** [Altinn/altinn-resource-registry#256]
### Description

Ref
Det må lages en løsning for å registrere/editere ressursene i 3.0. Dette skal gjøres via API, ref (#63)
Dette kan f eks være at tjenesteeier sender informasjon til oss og vi registrere dette via APIet
Det kan også gjøres vet at vi lager et GUI for tjenesteeier som deretter poster oppdateringer via APIet. 

### Additional Information

Functionality for administration through API is described here https://github.com/Altinn/altinn-resource-registry/issues/77

### Features

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/105
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/78
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/100
```

Denne tilhører epic: https://github.com/Altinn/altinn-authorization/issues/59

**Comment by TheTechArch** [comment]
Dekkes av https://github.com/Altinn/altinn-resource-registry/issues/130
