### ISSUE TITLE
Set up API managmenet for resource registry

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-resource-registry#26]
### Description

Set up API management for resource registry

### Additional Information

Process is partial described in Altinnpedia

### Tasks
- [x] Export Swagger
- [x] Create import files
- [x] Run import in DEV
- [x] Create export in DEV
- [x] Run import in AT
