### ISSUE TITLE
Cypress test for resource admin

### ISSUE THREAD

**Issue by WilliamThorenfeldt** [Altinn/altinn-resource-registry#274]
```[tasklist]
### Tasks
- [x] Creating resources from Resource admin main page
- [x] Verifying created resources are listed in Resource admin main page
- [ ] Verify searching of resources in Resource admin main page shows list as per searching
- [x] Editing resources from Resource admin main page
- [ ] Navigating back to dashboard after creating resources
- [ ] Publishing resources after making all required changes in resources
- [ ] Negative cypress tests for verifying resources are published only after all required fields are updated
```

```[tasklist]
### Tasks
```

**Comment by acn-Sneha** [comment]
@ernstjonny @annerisbakk @rtafj @anishastphen Siden Altinn Studio team har bestemt at de skal bruke playwright og de skal fjerne cypress testene. Da trenger vi ha testene i playwright ikke i cypress. Derfor lukker tasken.

**Comment by anishastphen** [comment]
@acn-Sneha skal studio teamet skrive testene i playwright for denne oppgaven?

**Comment by acn-Sneha** [comment]
@anishastphen nei, de skal ikke skrive testene for den. Vi trenger å skrive det i playwright da skal jeg lage en nye task med litt mer detaljer.
