### ISSUE TITLE
Resource Rights Registry 

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-resource-registry#337]
### Description

We need to establish a resource rights registry that allows resource owner the possibility to create registers of organizations that is allowed to access a resource. This is similar to SRR

### In scope

This covers both the creation of a resource rights registry and integrating it from PDP and Rights API.

### Analysis & Refinement

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/317
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/211
```

### Features

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/338
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/339
- [ ] PDP Should consier RRR for relevant resources
- [ ] Rights API should consider RRR for relevant resources
```

**Comment by TheTechArch** [comment]
Løses i https://github.com/Altinn/altinn-resource-registry/issues/131
