### ISSUE TITLE
Possible to administrate RRR from Altinn Studio

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-resource-registry#339]
## Description

Altinn should offer the possibility to administrate Resource Rights Registry from Altinn Studio

## User scenarios 
- A Altinn Studio user should be able to enable RRR for a resource in Altinn Studio 
- A user should be able to create a list of organizations to be used for RRR control for their organization
- A user should be able to connect list to resource and assign action

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/317
- [ ] https://github.com/Altinn/altinn-studio/issues/11642
- [ ] https://github.com/Altinn/altinn-studio/issues/11608
```

**Comment by Nyeng** [comment]
Lukkes etter refinement. 

@mgunnerud
