### ISSUE TITLE
PRP Endpoint for PDP

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-resource-registry#35]
### Description

The PDP needs an endpoint in the resource registry to consume policies for 

- Resources
- Apps
- 
### Additional Information

Do we need two endpoints? Or can we use same?

What about path

Should this policy be open? 

### Tasks
- [x] Decide one or two endpoints for policies (org/app and resource id)
- [x] Create Policy Controller with Get method

- [ ] Should this endpoint be open for anyone

### Acceptance Criteria
- [x] A endpoint for XACML policies should be exposed. It should be possible for PDP to get it with input of resourceid or appid

**Comment by jonkjetiloye** [comment]
Already delivered and tested as part of solution for migration of delegation schemes. Closing issue
