### ISSUE TITLE
Action filter support on AccessList Connection

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-resource-registry#446]
### Description

For å understøtte scenarioer hvor man skal skille mellom virksomheter som har lov til lese operasjoner og de som har lov til skrive operasjoner mot en ressurs må vi legge til støtte for Action Filter på en ressurs connection mellom ressurs og tilgangsliste (AccessList)

### Additional Information

I første omgang trenger vi ikke å tilby funksjonalitet i Altinn Studio for å sette et slikt filter. Dette kan vurderes legges til i etterkant hvis vi ser behov. 

### Tasks

- [ ] Legg støtte for Action Filter på connections
- [ ] List action filter for connections
- [ ] Oppdater PDP til å sjekke ActionFilter

**Comment by TheTechArch** [comment]
Jeg tror vi støtter dette.
