### ISSUE TITLE
Add langauge support for name of competent owner

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-resource-registry#62]
### Description

Add name to competent authorizty. Dictitionary with language support

### Additional Information

Add name to competent authorizty. Dictitionary with language support

### Tasks

- [x] Add name property to competent authorizty. Dictitionary with language support

_No response_

### Acceptance Criterias

- [x] Name property is present in competent authorizty. Dictitionary with language support
- [x] Get resource displays the name of the resource owner
- [x] Post operation saves the resource with resourceowner
- [ ] Is resourceowner mandatory?
